version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
=      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    networks:
      - postgres-network

  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@email.com'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    ports:
      - '16543:80'
    depends_on:
      - db
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
  # api:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_URL: postgres://root:123@db:5432/exercise
