version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: exercise
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
  # api:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #   environment:
  #     NODE_ENV: production
  #     DATABASE_URL: postgres://root:123@db:5432/exercise
